### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by nurmukhametov** [nmosier/rop-tools#1]
It looks like you forgot to add some header.
```
cc -c -g -Wall -pedantic   -c -o elfints.o elfints.c
elfints.c:19:10: fatal error: elfints.h: No such file or directory
 #include "elfints.h"
```

**Comment by nmosier** [comment]
Try installing `libelf`. It should be available from the package manager.

**Comment by nurmukhametov** [comment]
`libelf-dev` already installed, but it doesn't have `elfints.h`. 

The way you included it and its name let me to propose that this header is your internal project file. Don't you forget to add it?

**Comment by nmosier** [comment]
You're right -- it's been added. Try now. Sorry about that.

**Comment by nurmukhametov** [comment]
I guess same thing with 
```
#include "rop.tab.h" 
```

**Comment by nmosier** [comment]
That file should be generated by `bison` -- see `src/compiler/Makefile`. Do you have `bison` on your system?

**Comment by nurmukhametov** [comment]
Yes, I have `bison`. It looks like there is some dependencies problem in Makefile. But anyway, I generated `rop.tab.*`. 

Then I have another problem:
```
gcc -c -g -Wall -pedantic -o ropc.o ropc.c
ropc.c:18:10: fatal error: ropc.h: No such file or directory
 #include "ropc.h"
```

**Comment by nmosier** [comment]
Okay, it should compile now. I fixed the Makefile (dependencies for `ropc` were out-of-order), and I added `ropc.h`. Was able to do a fresh clone and compile from scratch.

**Comment by nurmukhametov** [comment]
Moreover, there is minor issue with some linkers:
```
gcc -lelf -lstdc++ -o elfints elfints.o ropelf.o ropbank.o util.o elfints_alg.o
ropelf.o: In function `ropelf_begin':
/home/oleshka/workspace/rop-tools/src/gadgets/ropelf.c:23: undefined reference to `elf_version'
/home/oleshka/workspace/rop-tools/src/gadgets/ropelf.c:29: undefined reference to `elf_begin'
/home/oleshka/workspace/rop-tools/src/gadgets/ropelf.c:35: undefined reference to `elf_kind'
/home/oleshka/workspace/rop-tools/src/gadgets/ropelf.c:36: undefined reference to `elf_end'
ropelf.o: In function `ropelf_end':
....
```
Which can be solved with reordering libraries with objects:
```
gcc -o elfints elfints.o ropelf.o ropbank.o util.o elfints_alg.o -lelf -lstdc++
```

I managed to build binaries `gadgets` and `ropc`.
